
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.prob.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.prob.item.UraniumItem;
import net.mcreator.prob.item.TriniumIngotItem;
import net.mcreator.prob.item.TitatiumIngotItem;
import net.mcreator.prob.item.TitanDioxydeItem;
import net.mcreator.prob.item.TinIngotItem;
import net.mcreator.prob.item.TinDustItem;
import net.mcreator.prob.item.TimerCircuitItem;
import net.mcreator.prob.item.StickyItem;
import net.mcreator.prob.item.SteelSwordItem;
import net.mcreator.prob.item.SteelShovelItem;
import net.mcreator.prob.item.SteelPickaxeItem;
import net.mcreator.prob.item.SteelIngotItem;
import net.mcreator.prob.item.SteelHoeItem;
import net.mcreator.prob.item.SteelAxeItem;
import net.mcreator.prob.item.SteelArmorItem;
import net.mcreator.prob.item.SteamItem;
import net.mcreator.prob.item.SimpleEnergyCellItem;
import net.mcreator.prob.item.SiliconItem;
import net.mcreator.prob.item.SaltDustItem;
import net.mcreator.prob.item.RocketItem;
import net.mcreator.prob.item.RefinedNaquadahDioxidItem;
import net.mcreator.prob.item.RPGItem;
import net.mcreator.prob.item.PolyvinylChlorideItem;
import net.mcreator.prob.item.PolypropileneItem;
import net.mcreator.prob.item.PolyethylenTetrafluorideItem;
import net.mcreator.prob.item.PolyethylenItem;
import net.mcreator.prob.item.PlatinaIngotItem;
import net.mcreator.prob.item.PlatinaDustItem;
import net.mcreator.prob.item.PhosphorusItem;
import net.mcreator.prob.item.P90Item;
import net.mcreator.prob.item.OxygenItem;
import net.mcreator.prob.item.OsmiumIngotItem;
import net.mcreator.prob.item.OsmiumDustItem;
import net.mcreator.prob.item.OilItem;
import net.mcreator.prob.item.NitrogenItem;
import net.mcreator.prob.item.NitricAcidItem;
import net.mcreator.prob.item.NickelIngotItem;
import net.mcreator.prob.item.NickelDustItem;
import net.mcreator.prob.item.NatriumIngotItem;
import net.mcreator.prob.item.NaquadahDustItem;
import net.mcreator.prob.item.MethanItem;
import net.mcreator.prob.item.MaronatronItem;
import net.mcreator.prob.item.LovesanimationItem;
import net.mcreator.prob.item.LithiumDustItem;
import net.mcreator.prob.item.KerozineItem;
import net.mcreator.prob.item.IronSawItem;
import net.mcreator.prob.item.IronDustItem;
import net.mcreator.prob.item.HydrogenItem;
import net.mcreator.prob.item.GasolineItem;
import net.mcreator.prob.item.FlintSwordItem;
import net.mcreator.prob.item.FlintShovelItem;
import net.mcreator.prob.item.FlintPickaxeItem;
import net.mcreator.prob.item.FlintHoeItem;
import net.mcreator.prob.item.FlintAxeItem;
import net.mcreator.prob.item.EthanItem;
import net.mcreator.prob.item.EnergyMeasureCircuitItem;
import net.mcreator.prob.item.ElectrometerItem;
import net.mcreator.prob.item.DetonatorItem;
import net.mcreator.prob.item.CopperIngotItem;
import net.mcreator.prob.item.CopperDustItem;
import net.mcreator.prob.item.ConductiveIronIngotItem;
import net.mcreator.prob.item.CobaltIngotItem;
import net.mcreator.prob.item.ChloreItem;
import net.mcreator.prob.item.CbDustItem;
import net.mcreator.prob.item.CapacitorCircuitItem;
import net.mcreator.prob.item.BronzeIngotItem;
import net.mcreator.prob.item.BitumenItem;
import net.mcreator.prob.item.AmmunitionItem;
import net.mcreator.prob.item.AmmoniumNitrateItem;
import net.mcreator.prob.item.AmmoniaItem;
import net.mcreator.prob.item.AluminiumIngotItem;
import net.mcreator.prob.item.AluminiumDustItem;
import net.mcreator.prob.ProbMod;

public class ProbModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ProbMod.MODID);
	public static final RegistryObject<Item> PLATINA_INGOT = REGISTRY.register("platina_ingot", () -> new PlatinaIngotItem());
	public static final RegistryObject<Item> PLATINA_ORE = block(ProbModBlocks.PLATINA_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> PLATINA_BLOCK = block(ProbModBlocks.PLATINA_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> COPPER_INGOT = REGISTRY.register("copper_ingot", () -> new CopperIngotItem());
	public static final RegistryObject<Item> COPPER_BLOCK = block(ProbModBlocks.COPPER_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> TIN_INGOT = REGISTRY.register("tin_ingot", () -> new TinIngotItem());
	public static final RegistryObject<Item> TIN_ORE = block(ProbModBlocks.TIN_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> TIN_BLOCK = block(ProbModBlocks.TIN_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> NAQUADAH_DUST = REGISTRY.register("naquadah_dust", () -> new NaquadahDustItem());
	public static final RegistryObject<Item> NAQUADAH_ORE = block(ProbModBlocks.NAQUADAH_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> NAQUADAH_BLOCK = block(ProbModBlocks.NAQUADAH_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> AMMUNITION = REGISTRY.register("ammunition", () -> new AmmunitionItem());
	public static final RegistryObject<Item> P_90 = REGISTRY.register("p_90", () -> new P90Item());
	public static final RegistryObject<Item> LOVESANIMATION = REGISTRY.register("lovesanimation", () -> new LovesanimationItem());
	public static final RegistryObject<Item> NICKEL_INGOT = REGISTRY.register("nickel_ingot", () -> new NickelIngotItem());
	public static final RegistryObject<Item> NICKEL_ORE = block(ProbModBlocks.NICKEL_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> NICKEL_BLOCK = block(ProbModBlocks.NICKEL_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> ROCKET = REGISTRY.register("rocket", () -> new RocketItem());
	public static final RegistryObject<Item> RPG = REGISTRY.register("rpg", () -> new RPGItem());
	public static final RegistryObject<Item> DETONATOR = REGISTRY.register("detonator", () -> new DetonatorItem());
	public static final RegistryObject<Item> C_4 = block(ProbModBlocks.C_4, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> ALUMINIUM_INGOT = REGISTRY.register("aluminium_ingot", () -> new AluminiumIngotItem());
	public static final RegistryObject<Item> ALUMINIUM_ORE = block(ProbModBlocks.ALUMINIUM_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> ALUMINIUM_BLOCK = block(ProbModBlocks.ALUMINIUM_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> OIL_BUCKET = REGISTRY.register("oil_bucket", () -> new OilItem());
	public static final RegistryObject<Item> MILITARY_CHEST = block(ProbModBlocks.MILITARY_CHEST, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> STEEL_INGOT = REGISTRY.register("steel_ingot", () -> new SteelIngotItem());
	public static final RegistryObject<Item> ALLOYSMELTERLVL_1 = block(ProbModBlocks.ALLOYSMELTERLVL_1, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> STEEL_BLOCK = block(ProbModBlocks.STEEL_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", () -> new SteelPickaxeItem());
	public static final RegistryObject<Item> STEEL_AXE = REGISTRY.register("steel_axe", () -> new SteelAxeItem());
	public static final RegistryObject<Item> STEEL_SWORD = REGISTRY.register("steel_sword", () -> new SteelSwordItem());
	public static final RegistryObject<Item> STEEL_SHOVEL = REGISTRY.register("steel_shovel", () -> new SteelShovelItem());
	public static final RegistryObject<Item> STEEL_HOE = REGISTRY.register("steel_hoe", () -> new SteelHoeItem());
	public static final RegistryObject<Item> STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", () -> new SteelArmorItem.Helmet());
	public static final RegistryObject<Item> STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate",
			() -> new SteelArmorItem.Chestplate());
	public static final RegistryObject<Item> STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", () -> new SteelArmorItem.Leggings());
	public static final RegistryObject<Item> STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", () -> new SteelArmorItem.Boots());
	public static final RegistryObject<Item> BRONZE_INGOT = REGISTRY.register("bronze_ingot", () -> new BronzeIngotItem());
	public static final RegistryObject<Item> BRONZE_BLOCK = block(ProbModBlocks.BRONZE_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> CONDUCTIVE_IRON_INGOT = REGISTRY.register("conductive_iron_ingot", () -> new ConductiveIronIngotItem());
	public static final RegistryObject<Item> CONDUCTIVE_IRON_BLOCK = block(ProbModBlocks.CONDUCTIVE_IRON_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> CRUSHERLVL_1 = block(ProbModBlocks.CRUSHERLVL_1, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> SILICON = REGISTRY.register("silicon", () -> new SiliconItem());
	public static final RegistryObject<Item> STEAM_BUCKET = REGISTRY.register("steam_bucket", () -> new SteamItem());
	public static final RegistryObject<Item> BOILER = block(ProbModBlocks.BOILER, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> INFINITE_WATER = block(ProbModBlocks.INFINITE_WATER, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> SURVIVALGENERATOR = block(ProbModBlocks.SURVIVALGENERATOR, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> ELECTROMETER = REGISTRY.register("electrometer", () -> new ElectrometerItem());
	public static final RegistryObject<Item> ALLOYSMELTERLVL_2 = block(ProbModBlocks.ALLOYSMELTERLVL_2, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> COPPER_ORE = block(ProbModBlocks.COPPER_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> NAQUADAH_GENERATOR = block(ProbModBlocks.NAQUADAH_GENERATOR, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> REFINED_NAQUADAH_DIOXID = REGISTRY.register("refined_naquadah_dioxid",
			() -> new RefinedNaquadahDioxidItem());
	public static final RegistryObject<Item> IRON_DUST = REGISTRY.register("iron_dust", () -> new IronDustItem());
	public static final RegistryObject<Item> NICKEL_DUST = REGISTRY.register("nickel_dust", () -> new NickelDustItem());
	public static final RegistryObject<Item> COPPER_DUST = REGISTRY.register("copper_dust", () -> new CopperDustItem());
	public static final RegistryObject<Item> ALUMINIUM_DUST = REGISTRY.register("aluminium_dust", () -> new AluminiumDustItem());
	public static final RegistryObject<Item> OSMIUM_INGOT = REGISTRY.register("osmium_ingot", () -> new OsmiumIngotItem());
	public static final RegistryObject<Item> OSMIUM_ORE = block(ProbModBlocks.OSMIUM_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> OSMIUM_BLOCK = block(ProbModBlocks.OSMIUM_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> OSMIUM_DUST = REGISTRY.register("osmium_dust", () -> new OsmiumDustItem());
	public static final RegistryObject<Item> DUSTSMELTER = block(ProbModBlocks.DUSTSMELTER, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> PLATINA_DUST = REGISTRY.register("platina_dust", () -> new PlatinaDustItem());
	public static final RegistryObject<Item> TIN_DUST = REGISTRY.register("tin_dust", () -> new TinDustItem());
	public static final RegistryObject<Item> CRUSHERLVL_2 = block(ProbModBlocks.CRUSHERLVL_2, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> OIL_REFINERY = block(ProbModBlocks.OIL_REFINERY, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> METHAN_BUCKET = REGISTRY.register("methan_bucket", () -> new MethanItem());
	public static final RegistryObject<Item> ETHAN_BUCKET = REGISTRY.register("ethan_bucket", () -> new EthanItem());
	public static final RegistryObject<Item> GASOLINE_BUCKET = REGISTRY.register("gasoline_bucket", () -> new GasolineItem());
	public static final RegistryObject<Item> KEROZINE_BUCKET = REGISTRY.register("kerozine_bucket", () -> new KerozineItem());
	public static final RegistryObject<Item> BITUMEN = REGISTRY.register("bitumen", () -> new BitumenItem());
	public static final RegistryObject<Item> URANIUM = REGISTRY.register("uranium", () -> new UraniumItem());
	public static final RegistryObject<Item> URANIUM_ORE = block(ProbModBlocks.URANIUM_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> URANIUM_BLOCK = block(ProbModBlocks.URANIUM_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> LITHIUM_DUST = REGISTRY.register("lithium_dust", () -> new LithiumDustItem());
	public static final RegistryObject<Item> LITHIUM_ORE = block(ProbModBlocks.LITHIUM_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> LITHIUM_BLOCK = block(ProbModBlocks.LITHIUM_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> FLINT_PICKAXE = REGISTRY.register("flint_pickaxe", () -> new FlintPickaxeItem());
	public static final RegistryObject<Item> FLINT_AXE = REGISTRY.register("flint_axe", () -> new FlintAxeItem());
	public static final RegistryObject<Item> FLINT_SWORD = REGISTRY.register("flint_sword", () -> new FlintSwordItem());
	public static final RegistryObject<Item> FLINT_SHOVEL = REGISTRY.register("flint_shovel", () -> new FlintShovelItem());
	public static final RegistryObject<Item> FLINT_HOE = REGISTRY.register("flint_hoe", () -> new FlintHoeItem());
	public static final RegistryObject<Item> STICKY = REGISTRY.register("sticky", () -> new StickyItem());
	public static final RegistryObject<Item> POLYETHYLEN = REGISTRY.register("polyethylen", () -> new PolyethylenItem());
	public static final RegistryObject<Item> POLYPROPILENE = REGISTRY.register("polypropilene", () -> new PolypropileneItem());
	public static final RegistryObject<Item> POLYVINYL_CHLORIDE = REGISTRY.register("polyvinyl_chloride", () -> new PolyvinylChlorideItem());
	public static final RegistryObject<Item> POLYETHYLEN_TETRAFLUORIDE = REGISTRY.register("polyethylen_tetrafluoride",
			() -> new PolyethylenTetrafluorideItem());
	public static final RegistryObject<Item> TITATIUM_INGOT = REGISTRY.register("titatium_ingot", () -> new TitatiumIngotItem());
	public static final RegistryObject<Item> TITATIUM_ORE = block(ProbModBlocks.TITATIUM_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> TITATIUM_BLOCK = block(ProbModBlocks.TITATIUM_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> SALT_DUST = REGISTRY.register("salt_dust", () -> new SaltDustItem());
	public static final RegistryObject<Item> SALT_ORE = block(ProbModBlocks.SALT_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> SALT_BLOCK = block(ProbModBlocks.SALT_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> TITAN_DIOXYDE = REGISTRY.register("titan_dioxyde", () -> new TitanDioxydeItem());
	public static final RegistryObject<Item> TIMER_CIRCUIT = REGISTRY.register("timer_circuit", () -> new TimerCircuitItem());
	public static final RegistryObject<Item> ENERGY_MEASURE_CIRCUIT = REGISTRY.register("energy_measure_circuit",
			() -> new EnergyMeasureCircuitItem());
	public static final RegistryObject<Item> CAPACITOR_CIRCUIT = REGISTRY.register("capacitor_circuit", () -> new CapacitorCircuitItem());
	public static final RegistryObject<Item> CHEMICAL_REACTOR = block(ProbModBlocks.CHEMICAL_REACTOR, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> IRON_SAW = REGISTRY.register("iron_saw", () -> new IronSawItem());
	public static final RegistryObject<Item> COBALT_INGOT = REGISTRY.register("cobalt_ingot", () -> new CobaltIngotItem());
	public static final RegistryObject<Item> COBALT_ORE = block(ProbModBlocks.COBALT_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> COBALT_BLOCK = block(ProbModBlocks.COBALT_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> CB_DUST = REGISTRY.register("cb_dust", () -> new CbDustItem());
	public static final RegistryObject<Item> OXYGEN_BUCKET = REGISTRY.register("oxygen_bucket", () -> new OxygenItem());
	public static final RegistryObject<Item> CHLORE_BUCKET = REGISTRY.register("chlore_bucket", () -> new ChloreItem());
	public static final RegistryObject<Item> HYDROGEN_BUCKET = REGISTRY.register("hydrogen_bucket", () -> new HydrogenItem());
	public static final RegistryObject<Item> NATRIUM_INGOT = REGISTRY.register("natrium_ingot", () -> new NatriumIngotItem());
	public static final RegistryObject<Item> NATRIUM_BLOCK = block(ProbModBlocks.NATRIUM_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> PHOSPHORUS = REGISTRY.register("phosphorus", () -> new PhosphorusItem());
	public static final RegistryObject<Item> MARONATRON = REGISTRY.register("maronatron", () -> new MaronatronItem());
	public static final RegistryObject<Item> NITROGEN_BUCKET = REGISTRY.register("nitrogen_bucket", () -> new NitrogenItem());
	public static final RegistryObject<Item> AMMONIUM_NITRATE = REGISTRY.register("ammonium_nitrate", () -> new AmmoniumNitrateItem());
	public static final RegistryObject<Item> AMMONIA_BUCKET = REGISTRY.register("ammonia_bucket", () -> new AmmoniaItem());
	public static final RegistryObject<Item> NITRIC_ACID_BUCKET = REGISTRY.register("nitric_acid_bucket", () -> new NitricAcidItem());
	public static final RegistryObject<Item> TRINIUM_INGOT = REGISTRY.register("trinium_ingot", () -> new TriniumIngotItem());
	public static final RegistryObject<Item> TRINIUM_ORE = block(ProbModBlocks.TRINIUM_ORE, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> TRINIUM_BLOCK = block(ProbModBlocks.TRINIUM_BLOCK, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> MACHINECHASISLVL_1 = block(ProbModBlocks.MACHINECHASISLVL_1, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> SIMPLE_ENERGY_CELL = REGISTRY.register("simple_energy_cell", () -> new SimpleEnergyCellItem());
	public static final RegistryObject<Item> PUMP = block(ProbModBlocks.PUMP, ProbModTabs.TAB_PROBAMOD);
	public static final RegistryObject<Item> REPLICATOR = REGISTRY.register("replicator_spawn_egg",
			() -> new ForgeSpawnEggItem(ProbModEntities.REPLICATOR, -6710887, -1, new Item.Properties().tab(ProbModTabs.TAB_PROBAMOD)));
	public static final RegistryObject<Item> MUD = block(ProbModBlocks.MUD, ProbModTabs.TAB_PROBAMOD);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
